nissan exercises for review
michael-o-imotor/nissan-exercises pull request #2
Opened 2022-07-27 07:10 UTC by michael-o-imotor

## Description

First PR for the onboarding Nissan exercises.

2022-07-28 11:10 UTC, pixelsoup requested changes
@michael-o-imotor 
Super solid work! Looks great. There's a lot going on here. Most of my feedback is repetitive, small and easy to fix (It looks worse than it is.

Asd discussed, please fix the nav primary font-size, dealer name font-size, logo size and nav primary active page. The header is where all the attention goes first. 

<img width="2040" alt="Screen Shot 2022-07-28 at 7 17 21 pm" src="https://user-images.githubusercontent.com/4155194/181491384-dcff3c5a-5682-46b2-9d4f-fad221439295.png">

You will need padding between vehicles here so the images and text never touch.

<img width="1268" alt="Screen Shot 2022-07-28 at 9 12 59 pm" src="https://user-images.githubusercontent.com/4155194/181492200-7a975359-18e3-4d81-86b4-f7aeb6766902.png">

2022-07-28 11:10 UTC, pixelsoup commented on includes/scss/_global.scss
> +.wrapper {
This class name is too generic. Either use .container (because it's everywhere in our sites - borrowed from bootstrap) or make up a more descriptive name like `wrapper-content` or `wrapper-site-content` to give meaning for other developers

2022-07-29 01:09 UTC, skatingincentralpark requested changes
Solid work, everything looks clean!  Just left a few comments that may be helpful.  👽

Also, not sure if you've heard of the author of below article, but this section has some interesting information on REMs vs PX ([Strategic Unit Deployment](https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/#strategic-unit-deployment)).  He's also written some other interesting articles on kinda advanced CSS and best practices.  Might be an interesting read for a train ride home.

2022-07-29 01:09 UTC, skatingincentralpark commented on includes/scss/_module-navara.scss
> +}
I would also drop the padding to `0 0 20px` here, as there's quite a gap on mobile

<img width="405" alt="Screen Shot 2022-07-29 at 10 59 12 am" src="https://user-images.githubusercontent.com/61100546/181661290-d6d0b968-e4a8-4953-b9d4-565b608e587f.png">

2022-08-01 00:41 UTC, merged